logFile: test.log
logLevel: INFO
msgFuncs:
- - SaveMsg_1
  - tag: SaveMsg
    contents: save1.txt
- - ModifyTopic_1
  - tag: ModifyTopic
    contents:
    - office/#
    - mountpoint_on_recv_office/office/light
- - saveMsg_2
  - tag: SaveMsg
    contents: save2.txt
brokers:
- brokerSubs:
  - mountpoint_office/mountpoint_on_recv_office/office/+
  brokerName: broker1
  brokerMount: mountpoint_home/
  brokerURI: mqtt://localhost:1883/mqtt
  brokerFwds:
  - home/room/temp
  connectType: MQTTConnection
- brokerSubs:
  - mountpoint_home/home/#
  brokerName: broker2
  brokerMount: mountpoint_office/
  brokerURI: mqtt://localhost:1885/mqtt
  brokerFwds:
  - office/light
  connectType: MQTTConnection
- brokerSubs:
  - home/+/temp
  - home/#
  brokerName: broker3
  brokerMount: ''
  brokerURI: tcp://localhost:19192
  brokerFwds:
  - home/ac/temp
  connectType: TCPConnection
- brokerSubs:
  - home/+/temp
  - home/#
  brokerName: broker4
  brokerMount: ''
  brokerURI: tcp://localhost:19193
  brokerFwds:
  - home/ac/temp
  connectType: TCPConnection
logToStdErr: true
